### ISSUE TITLE
Please document realtime push

### ISSUE THREAD

**Issue by jlooper** [Kinvey/nativescript-sdk#24]
How are we able to leverage realtime push, such as Firebase features. I believe it's available in the SDK but unsure how to use it. Are there examples?

thanks!

**Comment by gprodanov** [comment]
We had some issues with the NativeScript SDK, regarding Live Service. They have been resolved as of yesterday's release and Live Service should be usable in NativeScript. The docs for Live Service are [right here](https://devcenter.kinvey.com/nativescript/guides/live-service).

There's also a sample app [over here](https://github.com/kinveyapps/liveservice-js-sample). It is an Angular app for the browser, but since NativeScript can use Angular as well, it should be useful. There are no differences in the Live Service API between the platforms. The app also has (a simplified) live model binding, which sounds like the thing you're looking for (as it doesn't come out of the box with Live Service).
