### ISSUE TITLE
Android Push data not providing message

### ISSUE THREAD

**Issue by bradmartin** [Kinvey/nativescript-sdk#43]
Kinvey NS SDK: 3.11.6

Register for push using the documented process [here](https://devcenter.kinvey.com/nativescript/guides/push#push-register) using

```typescript
android: {
              senderID: '102XXXXXXXXX',
              notificationCallbackAndroid: (data, notification) => {
                console.log(data);
                console.log(notification);
              }
            },
```
Will log the following:

```bash
JS: {"foreground":true}
JS: com.google.firebase.messaging.RemoteMessage$Notification@14691ee
```

Even though the Push console was used to send `test`as a message.

![test](https://user-images.githubusercontent.com/6006148/45372798-76b2c180-b5b3-11e8-9d85-2cfc8b699288.png)

Not sure yet if I'm missing something in the docs or not. Any help appreciated 😄

**Comment by bradmartin** [comment]
I can get the body (message) in this case from the console if I use the RemoteMessage.Notification methods on the `notification` that is provided in the callback.

```typescript
   const x = notification.getBody();
```
So this works for now, I have not tested messages from business logic but in the process of doing so and will update with any info.

**Comment by bradmartin** [comment]
Can confirm that push sent via Business Logic  using `broadcastMessage` also only returns `{foreground: true}` when the app is in foreground. So only using the android firebase API can you get the message sent with this method.

@thomasconner hate to keep blowing you up, but any ideas or am I doing things incorrectly on my end?

**Comment by bradmartin** [comment]
I've switched a custom endpoint from using `sendMessage` to `sendPayload` and the push notification is never received. I toggle back to working `sendMessage` and I receive the notification.

**Comment by EddyVerbruggen** [comment]
Hey Brad! I was playing with notifications and found something similar. I think it would help to have the plugin process the notification internally and provide more info in the callback. I also found a way to get some relevant data from that `data` object. For instance, when using Postman to send a message like this to Android:

```json
{
  "notification": {
    "title": "I DEMAND YOUR ATTENTION :)",
    "subtitle": "Just kidding, but not really",
    "text": "Sorry to bother you I meant, please pick an option below.."
  },
  "content_available": false,
  "data": {
    "foo": "bar"
  },
  "priority": "High",
  "to": "THE_TOKEN"
}
```

The stuff in the `data` object above will get merged into the callback's `data` object, so now I received this while the app was in the foreground (as a `string` btw, not as an object): `{"foo":"bar","foreground":true}`

So the app can parse the `data` and use that for in-app logic.

When in the background, I was able to get the value of `foo` by adding this `resume` handler:

```typescript
import * as application from "tns-core-modules/application";

application.on(application.resumeEvent, (args: application.ApplicationEventData) => {
  if (args.android) {
    const activity = args.android;
    const intent = activity.getIntent();
    const extras = intent.getExtras();
    if (extras) {
      console.log(">> extras foo: " + extras.get("foo"));
    }
  }
});
```

IMO, ideally, when the app is resuming and received a notification while in the background it should trigger the callback handler as well (it currently doesn't, so that resume handler is needed).

WDYT?
